site_name: Foo

plugins:
    - hippogriffe
    - mkdocstrings:
        handlers:
            python:
                options:
                    force_inspection: true
                    inherited_members: true

nav:
    - 'foo.md'
